on:
  schedule:
    - cron: '0 0 * * *'
  release:
      types: [published]

env:
  REGISTRY: ghcr.io
  DBSP_IMAGE: ghcr.io/${{ github.repository_owner }}/dbsp-manager
  DEMO_IMAGE: ghcr.io/${{ github.repository_owner }}/demo-container

jobs:
  build-and-push-image:
    runs-on: [self-hosted, skylake40]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run integration tests
        run: |
          cd deploy && \
          SECOPS_DEMO_ARGS="--prepare-args 500000" docker compose -f docker-compose.yml -f docker-compose-dev.yml --profile demo up --build --force-recreate --exit-code-from demo

      # Disable until we bring the Kubernetes workflows up to speed
      # 
      # - uses: engineerd/setup-kind@v0.5.0
      #   with:
      #     version: "v0.11.1"
      #     skipClusterCreation: "true"

      # - name: Set up kind
      #   run: cd deploy/kind && ./setup.sh && ./setup.sh

      # - name: Deploy DBSP
      #   run: cd deploy/kind && sleep 60 && kubectl apply -f dbsp-deploy.yml && kubectl wait --for=condition=ready pod -l app=dbsp -n dbsp --timeout=300s

      - name: Log in to the Container registry
        if: github.event_name == 'release'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        if: github.event_name == 'release'
        run: |
          docker push ${{ env.DBSP_IMAGE }} && docker push ${{ env.DEMO_IMAGE }}
